//------------------------------------------------------------------------
// Copyright(c) 2025 MaxDev0101.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename "PitchControlDelay.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "PitchControlDelay VST3 (64Bit)"
#else
#define stringFileDescription "PitchControlDelay VST3"
#endif
#define stringCompanyName "MaxDev0101\0"
#define stringLegalCopyright "Copyright(c) 2025 MaxDev0101."
#define stringLegalTrademarks                                                  \
    "VST is a trademark of Steinberg Media Technologies GmbH"
